export const defaultEvents = [
  {
    id: 1,
    title: "Event 1",
    type: "question",
    date: "2022-12-30",
    time: "08:30",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    location: "Kyiv",
  },
  {
    id: 2,
    title: "Event 2",
    type: "conference",
    date: "2022-12-30",
    time: "08:30",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    location: "Odessa",
  },
  {
    id: 3,
    title: "Event 3",
    type: "meeting",
    date: "2022-12-30",
    time: "08:30",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    location: "Lviv",
  },
  {
    id: 4,
    title: "Event 4",
    type: "webinar",
    date: "2022-12-30",
    time: "08:30",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    location: "Kyiv",
  },
  {
    id: 5,
    title: "Event 5",
    type: "meeting",
    date: "2023-01-01",
    time: "08:30",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    location: "Lviv",
  },
];